#!/bin/sh

# docker-rm-unused-images
docker images --filter "dangling=true" -q --no-trunc | xargs --no-run-if-empty docker rmi

# docker-rm-unused-volumes
docker volume rm $(docker volume ls -qf dangling=true)

# docker-rm-stopped-containers
docker ps --filter "status=exited" -q --no-trunc | xargs --no-run-if-empty docker rm
